server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/student?characterEncoding = UTF-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update